create table PMS_BAT_PGM_M
(
    BAT_PGM_ID  VARCHAR(10) not null,
    BAT_PGM_NM  VARCHAR(30) not null,
    BAT_EXEC_DV_CD  VARCHAR(1) not null,
    BAT_EXEC_PRD_VAL  VARCHAR(6) null,
    FILE_INPT_YN  VARCHAR(1) not null,
    PRE_BAT_ID  VARCHAR(100) null,
    UZ_YN  VARCHAR(1) not null,
    FILE_ID  VARCHAR(10) null,
    EXEC_PARAM_CTNT  TEXT null,
    FRST_REG_TMST DATETIME not null,
    FRST_REG_EMPNO VARCHAR(6) not null,
    FRST_REG_BRCD VARCHAR(6) not null,
    LAST_CHNG_TMST DATETIME not null,
    LAST_CHNG_EMPNO VARCHAR(6) not null,
    LAST_CHNG_BRCD VARCHAR(6) not null,
    PRIMARY KEY (BAT_PGM_ID)
);

create table PMS_BAT_EXEC_L
(
    PUB_MDB_BAT_EXEC_SEQNO  BIGINT not null auto_increment,
    BAT_PGM_ID  VARCHAR(10) not null,
    BAT_EXEC_STS_CD  VARCHAR(1) not null,
    BAT_EXEC_FROM_TMST  DATETIME null,
    BAT_EXEC_TO_TMST  DATETIME null,
    BAT_EXEC_TOT_CNT  INTEGER null,
    BAT_EXEC_SCS_CNT  INTEGER null,
    BAT_EXEC_ERR_CNT  INTEGER null,
    BAT_EXEC_INPT_FILE_NM  VARCHAR(100) null,
    BAT_EXEC_OTPT_FILE_NM VARCHAR(100) null,
    FRST_REG_TMST DATETIME not null,
    FRST_REG_EMPNO VARCHAR(6) not null,
    FRST_REG_BRCD VARCHAR(6) not null,
    LAST_CHNG_TMST DATETIME not null,
    LAST_CHNG_EMPNO VARCHAR(6) not null,
    LAST_CHNG_BRCD VARCHAR(6) not null,
    PRIMARY KEY (PUB_MDB_BAT_EXEC_SEQNO)
);

ALTER TABLE PMS_BAT_EXEC_L ADD COLUMN BAT_EXEC_DT VARCHAR(8) AFTER PUB_MDB_BAT_EXEC_SEQNO;
ALTER TABLE PMS_BAT_EXEC_L ADD COLUMN BAT_EXEC_RSLT_CD VARCHAR(4) AFTER BAT_EXEC_FROM_TMST;
ALTER TABLE PMS_BAT_EXEC_L ADD COLUMN BAT_EXEC_RSLT_MSG_CTNT VARCHAR(100) AFTER BAT_EXEC_RSLT_CD;


SELECT * FROM pigeon_practice.PMS_BAT_PGM_M;
SELECT * FROM pigeon_practice.PMS_BAT_EXEC_L;